sudo: required
language: node_js

before_install:
- gem install sass
- gem install scss_lint
- npm install -g npm
- npm install promise
before_script:
- npm install -g gulp
script:
- gulp deploy
- npm test
- gulp coveralls

sudo: required
language: node_js
cache: npm
node_js:
- '8'
before_install:
- npm install -g npm
before_script:
- npm install -g gulp
script:
- gulp deploy
- gulp optimize
